services:
  nautical-backup:
    image: minituff/nautical-backup:latest
    container_name: nautical-backup
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ${DOCKER_DIR}/nautical-backup/config:/config 
      - ${DOCKER_DIR}:/app/source 
      - ${NFS_DIR}/${HOSTNAME}:/app/destination 
    environment:
      - TZ=${TZ}
      - CRON_SCHEDULE=0 1 * * * # daily at 1am
      - BACKUP_ON_START=false
